name: ğŸ“° Update Latest Substack Posts

on:
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    name: Fetch and update Substack articles
    steps:
      - name: ğŸ› ï¸ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ“° Pull latest posts from Substack
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://rss.app/feeds/wIiri3ZL4510LChc.xml"
          max_post_count: 3
          template: "- ğŸ”— [{{title}}]({{link}})"
